apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  containers:
    - name: testpvcwriter
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "Message at $(date)" >> /data/shared.txt;
            sleep 2;
          done
      volumeMounts:
        - name: volume1
          mountPath: /data

  volumeMounts:
    - name: volume1
      PersistentVolumeClaim:
      claimName: pvc-test1